// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: protos/comments.proto

package say_protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommentingClient is the client API for Commenting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentingClient interface {
	Post(ctx context.Context, in *PostComment, opts ...grpc.CallOption) (*Comment, error)
	Get(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*Comment, error)
}

type commentingClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentingClient(cc grpc.ClientConnInterface) CommentingClient {
	return &commentingClient{cc}
}

func (c *commentingClient) Post(ctx context.Context, in *PostComment, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, "/Commenting/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentingClient) Get(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, "/Commenting/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentingServer is the server API for Commenting service.
// All implementations must embed UnimplementedCommentingServer
// for forward compatibility
type CommentingServer interface {
	Post(context.Context, *PostComment) (*Comment, error)
	Get(context.Context, *GetParams) (*Comment, error)
	mustEmbedUnimplementedCommentingServer()
}

// UnimplementedCommentingServer must be embedded to have forward compatible implementations.
type UnimplementedCommentingServer struct {
}

func (UnimplementedCommentingServer) Post(context.Context, *PostComment) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedCommentingServer) Get(context.Context, *GetParams) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCommentingServer) mustEmbedUnimplementedCommentingServer() {}

// UnsafeCommentingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentingServer will
// result in compilation errors.
type UnsafeCommentingServer interface {
	mustEmbedUnimplementedCommentingServer()
}

func RegisterCommentingServer(s grpc.ServiceRegistrar, srv CommentingServer) {
	s.RegisterService(&Commenting_ServiceDesc, srv)
}

func _Commenting_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostComment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentingServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Commenting/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentingServer).Post(ctx, req.(*PostComment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commenting_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentingServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Commenting/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentingServer).Get(ctx, req.(*GetParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Commenting_ServiceDesc is the grpc.ServiceDesc for Commenting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Commenting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Commenting",
	HandlerType: (*CommentingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Post",
			Handler:    _Commenting_Post_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Commenting_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/comments.proto",
}
