# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comments.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63omments.proto\"f\n\x07\x43omment\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x18\n\x10outer_identifier\x18\x05 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x12\x13\n\x0breply_to_id\x18\x03 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t2*\n\nCommenting\x12\x1c\n\x04Post\x12\x08.Comment\x1a\x08.Comment\"\x00\x42,Z*github.com/SayIfOrg/say_protos/packages/gob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comments_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*github.com/SayIfOrg/say_protos/packages/go'
  _COMMENT._serialized_start=18
  _COMMENT._serialized_end=120
  _COMMENTING._serialized_start=122
  _COMMENTING._serialized_end=164
# @@protoc_insertion_point(module_scope)
